// auto generated by genTailwindConfig.ts
const theme = {
  "colors": {
    "bg-primary": "var(--bg-primary)",
    "text-primary": "var(--text-primary)",
    "text-secondary": "var(--text-secondary)"
  }
}
export default theme