import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import '@/styles/variables.css'
import './globals.css'
import clsx from 'clsx'
import { cookies } from 'next/headers'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  const cookiesStore = cookies()
  const theme = cookiesStore.get('theme')?.value || 'light'

  return (
    <html lang="en">
      <body className={clsx(inter.className, theme)}>{children}</body>
    </html>
  )
}
