import type { Metadata } from 'next'
import { dir } from 'i18next'
import clsx from 'clsx'
import { Inter } from 'next/font/google'
import { cookies } from 'next/headers'

import { languages } from '@/lib/i18n/settings'

import '@/styles/variables.css'
import '@/styles/globals.css'

export async function generateStaticParams() {
  return languages.map((lng) => ({ lng }))
}

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

type RootLayoutProps = {
  children: React.ReactNode
  params: { lng: string }
}
export default function RootLayout({ children, params: { lng } }: RootLayoutProps) {
  const cookiesStore = cookies()
  const theme = cookiesStore.get('theme')?.value || 'light'
  console.log('theme', theme)
  return (
    <html lang={lng} dir={dir(lng)}>
      <head />
      <body className={clsx(inter.className, theme)}>{children}</body>
    </html>
  )
}
